# Generated by Django 4.2.30 on 2026-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
